#!/usr/bin/env python3
"""The Folio launch film's sound, coded from the beat sheet. Standard library only.

    python3 video/folio/sound.py video/folio/out/cues.json video/folio/out/sound.wav

Every sound lands on a frame the picture already uses (cues.json is printed
from beats.ts), so a re-timed scene moves its sound with it. Nothing is
generated by a model: the picture identifies every sound (a tap, a tick, a
notification), so code is enough. A licensed track replaces the bed later;
the effects stay.

Act one: a soft kick on every beat, a tick on every hunt cut rising in pitch,
a thump under each slab of type, a ding per notification, a buzz for the
missed call, and a riser that stops dead on the switch. Act two: silence for
a breath, then a pad; each tap is a click and a two-note chime; each arriving
invoice a soft blip; the end card a low hit and the pad opening up.
"""

import json
import math
import random
import struct
import sys
import wave

SR = 48000
random.seed(7)


def load(path):
    with open(path) as fh:
        return json.load(fh)


class Bus:
    def __init__(self, seconds):
        self.n = int(seconds * SR)
        self.l = [0.0] * self.n
        self.r = [0.0] * self.n

    def add(self, at_s, samples, gain=1.0, pan=0.0):
        start = int(at_s * SR)
        gl = gain * math.cos((pan + 1) * math.pi / 4)
        gr = gain * math.sin((pan + 1) * math.pi / 4)
        for i, v in enumerate(samples):
            j = start + i
            if 0 <= j < self.n:
                self.l[j] += v * gl
                self.r[j] += v * gr


def env(i, n, attack, decay_tau):
    t = i / SR
    a = min(1.0, t / attack) if attack > 0 else 1.0
    return a * math.exp(-t / decay_tau) * (1 - i / n) ** 0.5


def sine_sweep(f0, f1, dur, attack=0.002, tau=0.08):
    n = int(dur * SR)
    out, ph = [], 0.0
    for i in range(n):
        f = f0 + (f1 - f0) * (i / n)
        ph += 2 * math.pi * f / SR
        out.append(math.sin(ph) * env(i, n, attack, tau))
    return out


def noise(dur, tau, hp=0.0):
    n = int(dur * SR)
    out, prev, prev_in = [], 0.0, 0.0
    for i in range(n):
        x = random.uniform(-1, 1)
        # One-pole high-pass so a click is a click and not a thud.
        y = hp * (prev + x - prev_in) if hp else x
        prev, prev_in = y, x
        out.append(y * env(i, n, 0.0005, tau))
    return out


def bell(freq, dur=0.6, tau=0.18):
    n = int(dur * SR)
    partials = [(1.0, 1.0), (2.0, 0.35), (3.01, 0.12)]
    return [
        sum(a * math.sin(2 * math.pi * freq * k * i / SR) for k, a in partials) * env(i, n, 0.003, tau / 1)
        for i in range(n)
    ]


def mix(*layers):
    n = max(len(x) for x in layers)
    return [sum(x[i] for x in layers if i < len(x)) for i in range(n)]


def kick(gain=1.0):
    return [v * gain for v in mix(sine_sweep(140, 42, 0.32, 0.001, 0.11), noise(0.012, 0.004, hp=0.9))]


def tick(freq):
    return mix(sine_sweep(freq, freq * 0.92, 0.07, 0.0005, 0.018), [v * 0.4 for v in noise(0.01, 0.003, hp=0.95)])


def tap():
    click = [v * 0.5 for v in noise(0.015, 0.004, hp=0.97)]
    pop = sine_sweep(900, 520, 0.09, 0.001, 0.03)
    return mix(click, pop)


def chime():
    a = bell(1046.5, 0.7, 0.16)  # C6
    b = bell(1568.0, 0.9, 0.22)  # G6, 80 ms later
    pad = int(0.08 * SR)
    return mix([v * 0.55 for v in a], [0.0] * pad + [v * 0.5 for v in b])


def ding():
    return mix([v * 0.5 for v in bell(1318.5, 0.5, 0.12)], [0.0] * int(0.06 * SR) + [v * 0.35 for v in bell(1975.5, 0.5, 0.12)])


def buzz(dur=0.42):
    n = int(dur * SR)
    out = []
    for i in range(n):
        t = i / SR
        tone = math.sin(2 * math.pi * 165 * t) + 0.4 * math.sin(2 * math.pi * 330 * t)
        am = 0.5 + 0.5 * math.sin(2 * math.pi * 28 * t)
        out.append(tone * am * env(i, n, 0.005, 0.5))
    return out


def riser(dur):
    n = int(dur * SR)
    out, ph, lp = [], 0.0, 0.0
    for i in range(n):
        p = i / n
        f = 180 * (4.5 ** p)
        ph += 2 * math.pi * f / SR
        x = random.uniform(-1, 1)
        lp += (0.02 + 0.5 * p * p) * (x - lp)
        out.append((0.35 * math.sin(ph) + 0.65 * lp) * (p ** 2.2))
    return out


def pad(dur, freqs, attack, release):
    n = int(dur * SR)
    out = []
    for i in range(n):
        t = i / SR
        a = min(1.0, t / attack) * min(1.0, (dur - t) / release)
        v = 0.0
        for k, f in enumerate(freqs):
            # Two detuned voices a note, a slow tremolo, so the calm is alive.
            v += math.sin(2 * math.pi * f * t) + math.sin(2 * math.pi * f * 1.003 * t + k)
        out.append(v / (2 * len(freqs)) * a * (0.9 + 0.1 * math.sin(2 * math.pi * 0.25 * t)))
    return out


def main(cues_path, out_path):
    c = load(cues_path)
    fps, beat = c["fps"], c["beat"]
    ev, sc = c["events"], c["scenes"]
    s = lambda frame: frame / fps  # noqa: E731
    bus = Bus(c["frames"] / fps + 1.0)

    # Act one: the grid, from the first slab of type to the switch.
    for frame in range(sc["collect"]["from"], ev["switch"], beat):
        bus.add(s(frame), kick(), 0.55)
    for frame in (sc["collect"]["from"], ev["twelveA"], ev["twelveB"], ev["weeks"]):
        bus.add(s(frame), kick(1.0), 0.7)
    for i, frame in enumerate(ev["huntCuts"]):
        bus.add(s(frame), tick(1500 + 110 * i), 0.32, pan=-0.35 if i % 2 else 0.35)
    for frame in ev["pileDrops"][:-1]:
        bus.add(s(frame), ding(), 0.42)
    # Each landing has weight: a low thump under the ding.
    for frame in ev["pileDrops"]:
        bus.add(s(frame), sine_sweep(90, 38, 0.4, 0.002, 0.14), 0.5)
    bus.add(s(ev["pileDrops"][-1]), buzz(), 0.4)
    rise_from = sc["pile"]["from"]
    bus.add(s(rise_from), riser(s(ev["switch"] - rise_from)), 0.32)

    # The first tap, at the top, before the grid starts.
    bus.add(s(ev["payTap"]), tap(), 0.6)
    bus.add(s(ev["payTap"] + 3), chime(), 0.5)

    # Act two: a breath of silence, then the pad. A major, low and wide.
    bed_from = ev["switch"] + beat // 2
    bed_dur = s(c["frames"] - bed_from)
    bus.add(s(bed_from), pad(bed_dur, [110.0, 164.81, 277.18], 1.6, 0.6), 0.16)
    for frame in (ev["approveTap"], ev["askTap"]):
        bus.add(s(frame), tap(), 0.6)
        bus.add(s(frame + 3), chime(), 0.5)
    notes = [1174.7, 1318.5, 1480.0, 1760.0, 1975.5, 2217.5, 2349.3, 2637.0]
    for i, frame in enumerate(ev["arriveDocs"]):
        bus.add(s(frame), sine_sweep(notes[i], notes[i] * 1.01, 0.18, 0.002, 0.05), 0.2, pan=0.2)
    bus.add(s(ev["arriveTotal"]), chime(), 0.35)

    # The end card: a low hit and the pad opening up a fifth.
    bus.add(s(ev["end"]), kick(1.0), 0.6)
    bus.add(s(ev["end"]), pad(s(c["frames"] - ev["end"]), [220.0, 329.63, 554.37, 659.25], 0.8, 0.8), 0.12)

    peak = max(max(abs(x) for x in bus.l), max(abs(x) for x in bus.r)) or 1.0
    g = 0.89 / peak
    with wave.open(out_path, "wb") as w:
        w.setnchannels(2)
        w.setsampwidth(2)
        w.setframerate(SR)
        frames = bytearray()
        for lv, rv in zip(bus.l, bus.r):
            frames += struct.pack("<hh", int(lv * g * 32767), int(rv * g * 32767))
        w.writeframes(bytes(frames))
    print(f"sound -> {out_path} ({bus.n / SR:.2f}s, peak normalised from {peak:.2f})")


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
