/*
 * Claude Adoption — 13-team skills grid (v3).
 *
 * Source of truth for the /claude-adoption page and the docs digest at
 * docs/claude-adoption-skills.md. Last reviewed 22 May 2026 against the
 * tightened Judgment-vs-Validation tagging rule (output shape decides).
 */

import type { CaTeamBlock } from "./claude-adoption";

export const caSkillsTeams: readonly CaTeamBlock[] = [
  {
    id: "legal",
    team: "Legal",
    workshopDate: "11 May workshop",
    phase: "encode",
    cards: [
      {
        id: "tracker-compliance-checker",
        title: "Tracker Compliance Checker",
        owner: "Herman",
        body: "Drives Chrome across Loop webshops and produces a weekly consent-violation report. Rule-based check against consent policy.",
        footnote: "v0.1 · extending to all webshops",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "validation",
      },
      {
        id: "nda-pre-check",
        title: "NDA Pre-Check",
        owner: "Olga + Vince",
        body: "Clause-by-clause review encoded. Catches routine deviations, routes novel cases to Legal. Unlocks four more pre-checks downstream.",
        footnote: "Starter Skill drafted, team refining",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "judgment",
      },
      {
        id: "legal-risk-methodology",
        title: "Legal Risk Methodology",
        owner: "Vince → team",
        body: "Loop risk methodology as substrate, starting with AI and Data Privacy. The engine all five Legal pre-checks call into.",
        footnote: "Substrate for 5 downstream Skills",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "judgment",
      },
      {
        id: "spa-pre-check",
        title: "SPA Pre-Check",
        owner: "Legal",
        body: "Same judgment-engine shape as NDA Pre-Check, applied to shareholder purchase agreements.",
        footnote: "Queued after NDA ships",
        status: "scoped",
        statusLabel: "SCOPED",
        substrate: "judgment",
      },
    ],
  },
  {
    id: "talent-acquisition",
    team: "Talent Acquisition",
    workshopDate: "May workshop",
    phase: "build",
    cards: [
      {
        id: "employer-branding-tov",
        title: "Employer Branding TOV",
        owner: "TA team",
        body: "Employer-facing tone encoded for job posts, outreach, and candidate comms. Pairs with People-team voice on internal side.",
        footnote: "Workshop in motion",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "voice",
      },
      {
        id: "candidate-screening",
        title: "Candidate Screening Brief",
        owner: "Maxim",
        body: "Structures intake notes into a consistent screening brief hiring managers can review in one pass.",
        footnote: "First encode from live reqs",
        status: "scoped",
        statusLabel: "SCOPED",
        substrate: "stakeholder",
      },
      {
        id: "interview-debrief",
        title: "Interview Debrief",
        owner: "Jenn",
        body: "Turns panel notes into a scored debrief against Loop hiring bars. Output is a score against a fixed rubric, which is the Validation shape.",
        footnote: "Pairs with Rhodes feedback Skill",
        status: "scoped",
        statusLabel: "SCOPED",
        substrate: "validation",
      },
    ],
  },
  {
    id: "finance",
    team: "Finance & Accounting",
    workshopDate: "8 May workshop",
    phase: "encode",
    cards: [
      {
        id: "variance-commentary",
        title: "Variance Commentary",
        owner: "Helen",
        body: "Month-end variance templates encoded. The Skill drafts the commentary, Helen reviews. Sounds like Helen. Structured inputs to templated narrative output.",
        footnote: "v0.1 in production · expanding to P&L narrative",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "pattern",
      },
      {
        id: "mec-tracker",
        title: "MEC Tracker",
        owner: "Jenny",
        body: "Month-end-close tracker in Claude as a Project. Carries forward month over month, surfaces blockers, drafts the status note.",
        footnote: "Project-mode automation",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "pattern",
      },
      {
        id: "gl-reconciliations",
        title: "GL Reconciliations",
        owner: "Finance",
        body: "SAP extract to reconciliation checks with anomaly flags. Same validation cluster as VAT.",
        footnote: "Validation cluster",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "validation",
      },
      {
        id: "belgian-vat-return",
        title: "Belgian VAT Return",
        owner: "Thijs",
        body: "SAP extract to VAT return automation. Replaces manual Excel Vlookups for the boxes.",
        footnote: "In pre-work",
        status: "scoped",
        statusLabel: "SCOPED",
        substrate: "validation",
      },
    ],
  },
  {
    id: "product-management",
    team: "Product Management",
    workshopDate: "setup 12 May · workshop ~26 May",
    phase: "build",
    cards: [
      {
        id: "product-ideation",
        title: "Product Ideation",
        owner: "Carlota + Vince",
        body: "Loop Vision Blueprint encoded as substrate. Pressure-tests raw ideas against portfolio, mission, value spaces, and roadmap.",
        footnote: "v0.1 for ~26 May workshop",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "judgment",
      },
    ],
  },
  {
    id: "program-management",
    team: "Program Management & Product",
    workshopDate: "12 May workshop",
    phase: "encode",
    cards: [
      {
        id: "program-status-updates",
        title: "Program Status Updates",
        owner: "Robert",
        body: "Reads transcripts, checks risk boards with program codes, reviews roadmap, drafts cross-team status digest.",
        footnote: "Work session booked",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "stakeholder",
      },
      {
        id: "risk-management",
        title: "Risk Management",
        owner: "Sander",
        body: "Standardizes risk descriptions, detects gaps, surfaces decision reasoning. Same engine shape as NDA Pre-Check.",
        footnote: "Work session booked",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "judgment",
      },
      {
        id: "vsme-sustainability-reporting",
        title: "VSME Sustainability Reporting",
        owner: "Vince → team",
        body: "Voluntary reporting standard for SMEs. Structured inputs to reporting template. Credible sustainability disclosures without a dedicated reporting function.",
        footnote: "EFRAG VSME · regulation track",
        status: "scoped",
        statusLabel: "SCOPED",
        substrate: "pattern",
      },
    ],
  },
  {
    id: "product-engineering",
    team: "Product Engineering",
    workshopDate: "workshop run",
    phase: "encode",
    cards: [
      {
        id: "daily-brief",
        title: "Daily Brief",
        owner: "Jennifer",
        body: "Pulls email, transcripts, and boards into one PE morning brief. Multi-source briefing pattern shared with Program Mgmt.",
        footnote: "Shared briefing substrate emerging",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "pattern",
      },
      {
        id: "brr-generator",
        title: "BRR Generator",
        owner: "PE team",
        body: "Generates Business Requirements Reviews from intake into the standardized PE template.",
        footnote: "Judgment-engine shape spanning four teams",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "judgment",
      },
    ],
  },
  {
    id: "warehousing",
    team: "Warehousing & Customer Ops",
    workshopDate: "13 May workshop",
    phase: "build",
    cards: [
      {
        id: "quality-auditor",
        title: "Quality Auditor",
        owner: "Toby + Maud",
        body: "Scores support tickets against Maud scorecard. Compares AI to human responses across BPOs. Batch trend report with outliers.",
        footnote: "v0.1 in use · scaling via Dixa API",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "validation",
      },
      {
        id: "fraud-detection",
        title: "Fraud Detection",
        owner: "Toby + Maud",
        body: "Pattern analysis on Shopify orders. Flags weird addresses, bot orders, suspicious refunds. Output is a flag list, which is the Validation shape.",
        footnote: "Implementation planning underway",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "validation",
      },
      {
        id: "invoice-processor",
        title: "Invoice Processor",
        owner: "Davy + Vince",
        body: "Supplier invoices across templates. Cross-checks vendor master, POs, prior invoices. Catches scam patterns.",
        footnote: "v0.1 drafted live",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "validation",
      },
      {
        id: "dashboard-consolidation",
        title: "Dashboard Consolidation",
        owner: "Rob + Samuel",
        body: "Harmonizes Klaviyo and Data Inzit into one exec-ready readout. Same briefing pattern plugs into Program Mgmt work.",
        footnote: "In use · cross-pollinating with Program Mgmt",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "pattern",
      },
    ],
  },
  {
    id: "people-ops",
    team: "People Ops",
    workshopDate: "8 May workshop",
    phase: "encode",
    cards: [
      {
        id: "people-team-voice",
        title: "People-team Voice",
        owner: "Thais",
        body: "Tone-of-voice Skill for playbook pages and internal comms. Built live from Thais TOV doc. Extending to emails and decks.",
        footnote: "v0.1 live · expanding scope",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "voice",
      },
      {
        id: "sop-generator",
        title: "SOP Generator",
        owner: "Gabriel",
        body: "Reverse-engineered from good Loop SOPs. Asks the question flow that elicits a complete SOP, drafts it for review.",
        footnote: "Working from existing examples",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "pattern",
      },
      {
        id: "onboarding-pops-processes",
        title: "Onboarding & POps Processes",
        owner: "Bernice",
        body: "Reasoning-first encoding of how People Ops handles edge cases. Includes celebration slides from interview transcripts.",
        footnote: "Reasoning before automation",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "judgment",
      },
      {
        id: "internal-loopers-personas",
        title: "Internal Loopers Personas",
        owner: "Astrid",
        body: "Employee personas for pressure-testing internal comms, playbook drafts, and policies before they go out. Simulates the reader rather than framing for one, so it does not fit Stakeholder.",
        footnote: "Possible sixth engine: pressure-test / simulation shape. Worth watching as more Skills land.",
        status: "in-build",
        statusLabel: "IN BUILD",
      },
    ],
  },
  {
    id: "brand-partnerships",
    team: "Brand & Partnerships",
    workshopDate: "13 May workshop",
    phase: "build",
    cards: [
      {
        id: "founder-tone-of-voice",
        title: "Founder Tone of Voice",
        owner: "Sayrade",
        body: "Loop founder voice encoded. Used for Tomorrowland prep and ongoing founder-led comms.",
        footnote: "In production use",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "voice",
      },
      {
        id: "partnership-inbox-filter",
        title: "Partnership Inbox Filter",
        owner: "Nathalie + Stan + Vince",
        body: "Classifies partnership requests by tier using gradient examples. Drafts the tier-appropriate response. Output is a draft with reasoning.",
        footnote: "v0.1 with Nathalie + Stan",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "judgment",
      },
      {
        id: "360-marketing-agent",
        title: "360 Marketing Agent",
        owner: "Yalis",
        body: "Porting Yalis ChatGPT custom GPT into a Claude Skill for sharing, versioning, and wider Loop workflows.",
        footnote: "Migration in progress · Mímir consumer",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "pattern",
      },
      {
        id: "retail-marketing-calendar",
        title: "Retail Marketing Calendar",
        owner: "Pixie",
        body: "One year, every retailer. Built in Claude Design, plugged into Mímir as live database PMM team owns together. This is a content asset Mímir consumes, not an inputs-to-output engine.",
        footnote: "5 retailers · 16 events · running in Mímir",
        status: "in-use",
        statusLabel: "IN USE",
      },
      {
        id: "paid-social-tov",
        title: "Paid Social TOV",
        owner: "Brand",
        body: "Paid social copy rules encoded so campaign drafts stay on-brand before human review.",
        footnote: "Voice cluster with founder TOV",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "voice",
      },
    ],
  },
  {
    id: "strategic-insights",
    team: "Strategic Insights",
    workshopDate: "May workshop",
    phase: "encode",
    cards: [
      {
        id: "market-scan-brief",
        title: "Market Scan Brief",
        owner: "Kuhn",
        body: "Structures competitive and category signals into a standing brief format the insights team can refresh weekly.",
        footnote: "First encode from live scan workflow",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "stakeholder",
      },
      {
        id: "survey-synthesis",
        title: "Survey Synthesis",
        owner: "Insights",
        body: "Turns raw survey exports into themed readouts with quoted evidence and confidence notes.",
        footnote: "Stakeholder-shape for leadership readouts",
        status: "scoped",
        statusLabel: "SCOPED",
        substrate: "stakeholder",
      },
      {
        id: "trend-scraper",
        title: "Trend Scraper",
        owner: "Insights · Cowork",
        body: "Pulls external trend signals into a digest the team can route into briefing and calendar workflows.",
        footnote: "Lives in Cowork surface",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "pattern",
      },
    ],
  },
  {
    id: "manufacturing-programs",
    team: "Manufacturing Programs",
    workshopDate: "May workshop",
    phase: "encode",
    cards: [
      {
        id: "lead-time-calculator",
        title: "Lead Time Calculator",
        owner: "Alice",
        body: "Encodes lead-time rules across suppliers and lanes so program dates stay honest in planning conversations.",
        footnote: "Pattern: rules + inputs to fielded output",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "pattern",
      },
      {
        id: "cost-feasibility-portfolio",
        title: "Cost / Feasibility / Portfolio",
        owner: "Elodie + Alice",
        body: "Manufacturing-side triage on cost, feasibility, and portfolio fit. Shares judgment-engine DNA with design triage.",
        footnote: "Cross-team judgment cluster",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "judgment",
      },
      {
        id: "supplier-qa-audit",
        title: "Supplier QA Audit",
        owner: "Manufacturing",
        body: "Scores supplier QA reports against Loop bars. Validation cluster alongside warehousing quality work.",
        footnote: "Validation emerging",
        status: "scoped",
        statusLabel: "SCOPED",
        substrate: "validation",
      },
    ],
    moreTail: "+ localization, BOM checks in backlog",
  },
  /* Product Design + Studio sit at the bottom of the team list so
     the green-highlighted Skills they own (CMF File Generator,
     Packaging Review is in Manufacturing Programs above, Loop
     Paid Social below) cluster directly above the Build phase
     section that follows. The reader scrolls past the green wash,
     then enters Tools → Mímir + Vesper which compose exactly
     those Skills. Reorder added for that bridge. */
  {
    id: "product-design",
    team: "Product Design & UX",
    workshopDate: "30 Apr workshop · 14 May follow-up",
    phase: "build",
    cards: [
      {
        id: "cmf-file-generator",
        title: "CMF File Generator",
        owner: "Damien",
        body: "Excel schema in, manufacturer-ready PDF with cloud renders out. Wired into Vesper for end-to-end CMF generation.",
        footnote: "v0.1 shipped 30 Apr",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "pattern",
        feedsBuildPhase: true,
      },
      /* Loop Packaging System — end-to-end automation for the
         packaging production workflow (editable Illustrator files +
         Excel workbook → supplier-ready PDFs, info-box overlays,
         Creative Intent brief, organised stage folders for
         EVT/DVT/PVT/MP). Replaces the narrower "Packaging Review"
         framing that lived under Manufacturing Programs. Owned
         out of Product Design because designers ship the
         artwork + brief together; pairs with Vesper's CMF File
         Generator on the build-phase tools row below. Source
         skill at tensalir/loop-skills/loop-packaging-system. */
      {
        id: "loop-packaging-system",
        title: "Loop Packaging System",
        owner: "Ana",
        body: "End-to-end automation for Loop\u2019s packaging production. Editable Illustrator files plus an Excel workbook in, supplier-ready PDFs with info-box overlays plus the wrap-around Creative Intent brief out. Promotes EVT \u2192 DVT \u2192 PVT \u2192 MP folder structures.",
        footnote: "Pairs with CMF on Vesper",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "pattern",
        feedsBuildPhase: true,
      },
      {
        id: "ux-foundations-evaluation",
        title: "UX Foundations Evaluation",
        owner: "Aurélie",
        body: "Reads a concept and returns alignment against Loop six UX pillars: Elevated, Nonconformist, Empowering, and the rest.",
        footnote: "v0.1 after foundations PDF + transcript",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "judgment",
      },
      {
        id: "sketch-to-digital-twin",
        title: "Sketch to Digital Twin",
        owner: "Tibo",
        body: "Converts 2D sketches into 3D digital twins. Modality conversion; does not fit one of the five engines.",
        footnote: "Ready to encode as Skill",
        status: "shipped",
        statusLabel: "SHIPPED",
      },
      {
        id: "concept-triage-engine",
        title: "Concept Triage Engine",
        owner: "Elodie",
        body: "Three Skills, one engine: cost estimation, feasibility, portfolio fit. Four design checks as one architectural move.",
        footnote: "3 Skills in 1 build",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "judgment",
      },
      {
        id: "product-review-analysis",
        title: "Product Review Analysis",
        owner: "Mattis",
        body: "Amazon review scraping and structured analysis. Surfaces themes and request patterns across markets.",
        footnote: "Reusable for Rakuten and beyond",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "pattern",
      },
    ],
    moreTail: "+ Visual Persona, Context Mapping in backlog",
  },
  {
    id: "performance",
    team: "Performance",
    workshopDate: "May workshop",
    phase: "encode",
    cards: [
      /* The Loop Creative Strategy substrate — four axes (Reiss
         desire, Life Force 8, awareness stage, transformation arc)
         plus ten hook archetypes — that Mímir composes off. The
         skill bundle lives at tensalir/loop-skills/loop-creative-
         strategy. Marked feedsBuildPhase so the card carries the
         03 · BUILD pill and the green wash above the Tools section
         that uses it. */
      {
        id: "loop-creative-strategy",
        title: "Loop Creative Strategy",
        owner: "Chloe",
        body: "The creative-strategy substrate Loop runs on: four axes (Reiss desire, Life Force 8, awareness stage, transformation arc) plus ten hook archetypes, applied to every review, ad, and brief. M\u00edmir composes off this engine.",
        footnote: "Feeds the M\u00edmir composer",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "judgment",
        feedsBuildPhase: true,
      },
    ],
  },
  {
    id: "studio",
    team: "Studio",
    workshopDate: "May workshop",
    phase: "encode",
    cards: [
      {
        id: "feedback-summarizer",
        title: "Feedback Summarizer",
        owner: "Rhodes",
        body: "Turns creative feedback threads into a structured summary stakeholders can act on without re-reading Slack.",
        footnote: "Cowork + stakeholder-shape",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "stakeholder",
      },
      {
        id: "localization",
        title: "Localization",
        owner: "Studio",
        body: "Locale-aware copy checks against approved translations. Pairs with Loop Figma localization repair workflows.",
        footnote: "Encode in progress",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "validation",
      },
      {
        id: "asset-brief-generator",
        title: "Asset Brief Generator",
        owner: "Rhodes",
        body: "Drafts studio briefs from campaign inputs so producers start from a complete spec, not a blank doc.",
        footnote: "Pattern composition with brand guidelines",
        status: "in-build",
        statusLabel: "IN BUILD",
        substrate: "pattern",
      },
      {
        id: "it-access-runbook",
        title: "IT Access Runbook",
        owner: "Kelly",
        body: "Encodes IT onboarding steps and access checks so Studio and PE requests route with fewer round-trips. SOP-adjacent but borderline; leave untagged until a sibling lands.",
        footnote: "IT folded into Studio beat",
        status: "scoped",
        statusLabel: "SCOPED",
      },
      /* Three voice-shape Skills produced out of Studio that encode
         Loop's brand voice across the marketing surfaces it doesn't
         author directly. Each is a packaged SKILL bundle in
         tensalir/loop-skills: SKILL.md plus framework /compliance /
         references / voice sub-folders. The paid-social entry feeds
         the Mímir tool below (via the `consumes` list in
         caToolsSection — see content/claude-adoption.ts) and so
         carries `feedsBuildPhase: true` for the sage-green wash. */
      {
        id: "loop-paid-social",
        title: "Loop Paid Social",
        owner: "Chloe",
        body: "Paid social ad copy for Loop Earplugs, grounded in 295 real ads across every product, audience angle, seasonal campaign, and brand collab. Generates Meta primary text, headlines, descriptions, and DPA copy in Loop voice with compliance baked in.",
        footnote: "Feeds the M\u00edmir composer",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "voice",
        feedsBuildPhase: true,
      },
      {
        id: "loop-crm",
        title: "Loop CRM",
        owner: "CRM",
        body: "CRM communications across the customer lifecycle. Onboarding, retention, support escalations, win-back, loyalty. Loop voice with GDPR / CAN-SPAM / TCPA guardrails encoded into the Skill, not bolted on after.",
        footnote: "Lifecycle copy, end-to-end",
        status: "shipped",
        statusLabel: "SHIPPED",
        substrate: "voice",
      },
      {
        id: "loop-marketplace",
        title: "Loop Marketplace",
        owner: "Marketplace",
        body: "Amazon marketplace copy for Loop products. Titles, SEO descriptions, bullets, A+ content modules, and PDP image text. Adapts base copy for collabs (Coachella, Tomorrowland), bundles, and new colourways via the proven substitution patterns.",
        footnote: "Amazon listing copy",
        status: "shipped",
        statusLabel: "SHIPPED",
        substrate: "voice",
      },
      /* Prompt patterns for AI image and video generation — the
         execution-layer companion to the Creative Strategy substrate
         in the Performance team above. Covers semantic prompting
         (Nano Banana, GPT Image, Seedream), descriptive prompting
         (Midjourney, Flux), reference image roles, and Andromeda-
         aware ad iteration. Lives at tensalir/loop-skills/
         genai-prompting. */
      {
        id: "genai-prompting",
        title: "GenAI Prompting",
        owner: "Studio",
        body: "How Loop gets useful work out of AI image and video tools. Knows which models want a story and which want keyword density, uses reference images without copying them, and turns one campaign idea into a slate of distinct ads.",
        footnote: "Image + video prompts",
        status: "in-use",
        statusLabel: "IN USE",
        substrate: "pattern",
      },
    ],
  },
] as const;
